services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: reelmetrics_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_BROKER_ID: 1
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CFG_MESSAGE_MAX_BYTES: 200000000
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: 200000000
      KAFKA_CFG_SOCKET_REQUEST_MAX_BYTES: 200000000
    depends_on:
      - zookeeper
            
  backend_python:
    build: ./backend_python
    container_name: backend_python
    restart: always
    depends_on:
      - postgres
      - redis
      - kafka
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/reelmetrics_db"
      REDIS_URL: "redis://redis:6379/0"
      KAFKA_BROKER: "kafka:9092"

  backend_go:
    build: ./backend_go
    container_name: backend_go
    restart: always
    depends_on:
      - postgres
      - redis
      - kafka
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/reelmetrics_db"
      REDIS_URL: "redis://redis:6379/0"
      KAFKA_BROKER: "kafka:9092"

  event_consumer:
    build: ./event_consumer
    container_name: event_consumer
    restart: always
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      POSTGRES_DB: "reelmetrics_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_HOST: "postgres"
      REDIS_HOST: "redis"
      KAFKA_BROKER: "kafka:9092"

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    depends_on:
      - backend_python
      - backend_go
    ports:
      - "3000:3000"

volumes:
  postgres_data:
    driver: local
